name: Unit Tests

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: "actions/checkout@v2"
      - name: "Set up Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          python -m pip install -e .
      - name: "Install testing suite"
        run: |
          python -m pip install pytest>=6.2.5
          python -m pip install coverage>=6.2
      - name: "Run tests and collect coverage"
        run: |
          coverage run -m pytest unit_tests
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
